// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccdrHi9VuJNtWN_J5TymbFlvnnFsaLGM',
    appId: '1:133894196998:web:bd33644572806e0d2d9887',
    messagingSenderId: '133894196998',
    projectId: 'camions-9050e',
    authDomain: 'camions-9050e.firebaseapp.com',
    storageBucket: 'camions-9050e.firebasestorage.app',
    measurementId: 'G-HJVHS44M3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq3irhos0_xeKY-x5_phwtf2vVrv-NoLg',
    appId: '1:133894196998:android:eaf129ef2aa13a462d9887',
    messagingSenderId: '133894196998',
    projectId: 'camions-9050e',
    storageBucket: 'camions-9050e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC0bF7T9JJ2Gnr6IhdgsDYuIJIjg6Zzow',
    appId: '1:133894196998:ios:05e059022cc02c812d9887',
    messagingSenderId: '133894196998',
    projectId: 'camions-9050e',
    storageBucket: 'camions-9050e.firebasestorage.app',
    iosBundleId: 'com.fleetguard.fleetguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC0bF7T9JJ2Gnr6IhdgsDYuIJIjg6Zzow',
    appId: '1:133894196998:ios:03ad2c937e870ac12d9887',
    messagingSenderId: '133894196998',
    projectId: 'camions-9050e',
    storageBucket: 'camions-9050e.firebasestorage.app',
    iosBundleId: 'com.fleetguard.fleetguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCccdrHi9VuJNtWN_J5TymbFlvnnFsaLGM',
    appId: '1:133894196998:web:9f596b81b9023d1c2d9887',
    messagingSenderId: '133894196998',
    projectId: 'camions-9050e',
    authDomain: 'camions-9050e.firebaseapp.com',
    storageBucket: 'camions-9050e.firebasestorage.app',
    measurementId: 'G-SXH1NQPMJV',
  );
}
